export default class Routes {
  static home = '/'
  static dfa = '/dfa'
  static nfa = '/nfa'
  static regex = '/regex'
  static cfg = '/cfg'
  static pda = '/pda'
  static dnfaGenerator = '/dnfa/generator'
  static dnfaInput = '/dnfa/input'
  static regexInput = '/regex/input'
  static cfgInput = '/cfg/input'
  static pdaGenerator = '/pda/generator'
  static pdaInput = '/pda/input'
  static dfaAnswer = '/dfa/answer'
  static regexAnswer = '/regex/answer'
  static cfgAnswer = '/cfg/answer'
  static pdaAnswer = '/pda/answer'
  static setsAnswer = '/sets/answer'
  static tableAnswer = '/table/answer'
}
